name: Deploy Static Site

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        id: checkout
        uses: actions/checkout@v3
      - name: Build Site
        id: build
        run: npm install && npm run build
      - name: Setup Pages
        id: setup
        uses: actions/configure-pages@v3
      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1
